package paquete;
import java.sql.*;
import javax.swing.table.*;

public class VentanaPrincipal extends javax.swing.JFrame {

    public String calculoNota(float notafinal){
            String a = null;
            if(notafinal >= 7){
                a="Promocionado";
            } else{
                if(notafinal < 4){
                    a="Libre";
                } else{
                    a="Regular";
                }
            }
            
            
            return a;
        }
    
    public String calculoResultado(int nota1, int nota2){
        String a = null;
        
        if(nota1 >= 7 && nota2 >= 7){
            a="Promocionado";
        } else{
            if(nota1 < 4 || nota2 < 4){
                a="Libre";
            } else{
                a="Regular";
            }
        }
        
        return a;
    }
    
    public void cargarTabla(){
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            
            String sql = "select * from listaalumnos";
            ResultSet res = s.executeQuery(sql);
            
            DefaultTableModel datos = (DefaultTableModel)jTable1.getModel();
            datos.setNumRows(0);
            while(res.next()){
                Object[] vector = new Object[5];
                vector[0] = res.getString("legajo");
                vector[1] = res.getString("nombre");
                vector[2] = res.getString("nota1");
                vector[3] = res.getString("nota2");
                vector[4] = res.getString("resultado");
                datos.addRow(vector);
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }
    
    public VentanaPrincipal() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Legajo", "Nombre", "Nota 1", "Nota 2", "Resultado"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Legajo: ");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Parcial 1: ");

        jLabel4.setText("Parcial 2: ");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Promoc.");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Regul.");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Libre");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Listar Todos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNota2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNota1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            //float notafinal = ( Integer.parseInt(txtNota1.getText()) + Integer.parseInt(txtNota2.getText()) ) / 2;
            int nota1 = Integer.parseInt(txtNota1.getText());
            int nota2 = Integer.parseInt(txtNota2.getText());
            String sql =
                    "INSERT INTO listaalumnos(legajo,nombre,nota1,nota2,resultado) values('%1','%2','%3','%4','%5')"
                    .replace("%1", txtLegajo.getText())
                    .replace("%2", txtNombre.getText())
                    .replace("%3", txtNota1.getText())
                    .replace("%4", txtNota2.getText())
                    .replace("%5", calculoResultado(nota1,nota2));
            int res = s.executeUpdate(sql);
            System.out.println(res);
        } catch(Exception e){
            System.out.println(e);
        }
        cargarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            
            int nota1 = Integer.parseInt(txtNota1.getText());
            int nota2 = Integer.parseInt(txtNota2.getText());
            
            //float notafinal = ( Integer.parseInt(txtNota1.getText()) + Integer.parseInt(txtNota2.getText()) ) / 2;
            
            String sql = "update listaalumnos set nombre='%2', nota1='%3', nota2='%4', resultado='%5' where legajo='%1'";
            sql = sql.replace("%1", txtLegajo.getText());
            sql = sql.replace("%2", txtNombre.getText());
            sql = sql.replace("%3", txtNota1.getText());
            sql = sql.replace("%4", txtNota2.getText());
            //sql = sql.replace("%5", calculoNota(notafinal));
            sql = sql.replace("%5", calculoResultado(nota1, nota2));
            System.out.println(sql);
            s.executeUpdate(sql);
            cargarTabla();
        } catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            String sql = "delete from listaalumnos where legajo=%1";
            sql = sql.replace("%1", txtLegajo.getText());
            System.out.println(sql);
            s.executeUpdate(sql);
            cargarTabla();
        } catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
        String legajo = datos.getValueAt(row, 0).toString();
        txtLegajo.setText(legajo);
        txtNombre.setText(datos.getValueAt(row, 1).toString());
        txtNota1.setText(datos.getValueAt(row, 2).toString());
        txtNota2.setText(datos.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            
            
            String sql = "select * from listaalumnos where resultado='%1' ";
            sql = sql.replace("%1", "Promocionado");
            
            ResultSet res = s.executeQuery(sql);
            
            DefaultTableModel datos = (DefaultTableModel)jTable1.getModel();
            datos.setNumRows(0);
            while(res.next()){
                Object[] vector = new Object[5];
                vector[0] = res.getString("legajo");
                vector[1] = res.getString("nombre");
                vector[2] = res.getString("nota1");
                vector[3] = res.getString("nota2");
                vector[4] = res.getString("resultado");
                datos.addRow(vector);
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            
            
            String sql = "select * from listaalumnos where resultado='%1' ";
            sql = sql.replace("%1", "Regular");
            
            ResultSet res = s.executeQuery(sql);
            
            DefaultTableModel datos = (DefaultTableModel)jTable1.getModel();
            datos.setNumRows(0);
            while(res.next()){
                Object[] vector = new Object[5];
                vector[0] = res.getString("legajo");
                vector[1] = res.getString("nombre");
                vector[2] = res.getString("nota1");
                vector[3] = res.getString("nota2");
                vector[4] = res.getString("resultado");
                datos.addRow(vector);
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            
            
            String sql = "select * from listaalumnos where resultado='%1' ";
            sql = sql.replace("%1", "Libre");
            
            ResultSet res = s.executeQuery(sql);
            
            DefaultTableModel datos = (DefaultTableModel)jTable1.getModel();
            datos.setNumRows(0);
            while(res.next()){
                Object[] vector = new Object[5];
                vector[0] = res.getString("legajo");
                vector[1] = res.getString("nombre");
                vector[2] = res.getString("nota1");
                vector[3] = res.getString("nota2");
                vector[4] = res.getString("resultado");
                datos.addRow(vector);
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/notas", "root", "");
            Statement s = c.createStatement();
            
            String sql = "select * from listaalumnos";
            ResultSet res = s.executeQuery(sql);
            
            DefaultTableModel datos = (DefaultTableModel)jTable1.getModel();
            datos.setNumRows(0);
            while(res.next()){
                Object[] vector = new Object[5];
                vector[0] = res.getString("legajo");
                vector[1] = res.getString("nombre");
                vector[2] = res.getString("nota1");
                vector[3] = res.getString("nota2");
                vector[4] = res.getString("resultado");
                datos.addRow(vector);
            }
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    // End of variables declaration//GEN-END:variables
}
